### ISSUE TITLE
Uno wifi , Should I use 2.4.0-rc2 or 2.4 version for esp8266 part?

### ISSUE THREAD

**Issue by kalsolio** [jandrassy/UnoWiFiDevEdSerial1#2]
I saw you change Wiki doc of esp8266. Should I use 2.4.0-rc2 or 2.4 version?

I saw origin said Use lwip v2 by default, But we use LwIP v1.4 Prebuilt and have a lower CPU frequency 80 MHz.

**Comment by JAndrassy** [comment]
The 2.4 was released 1.1. I tested it with WiFi Link. With lwip 2 it was not working well. Web Panel sometimes hang and the WebClient example did not show the complete logo.
I didn't know what is the 160 MHz setting. Now I have confirmation from core developer, that the core sets the speed of esp to 160 MHz if it is selected. I didn't try it yet. 
I you can test 2.4, use 2.4. If you do not want surprises use rc2.

**Comment by kalsolio** [comment]
Thank you for your patience.

**Comment by kalsolio** [comment]
http://bbs.espressif.com/viewtopic.php?t=889#p3050
![tim 20180104160544](https://user-images.githubusercontent.com/14342288/34554693-21f734c8-f169-11e7-8275-2a1c319da998.png)
