### ISSUE TITLE
Missing .bin files

### ISSUE THREAD

**Issue by vsavic** [jandrassy/UnoWiFiDevEdSerial1#3]
What exactly should be `boot_v1.7.bin` and `blank.bin`? 
When I download zip from  Espressif download page  these files are not there, so when I run `esptool.py` it reports that they are missing.

Can you please post links to these two files?

**Comment by JAndrassy** [comment]
![screenshot from 2018-06-24 06-59-48](https://user-images.githubusercontent.com/10706773/41816100-4aaf042e-777c-11e8-9633-ad396643b06c.png)

**Comment by vsavic** [comment]
You were right, my bad, I was just looking at `AT` folder instead of `BIN`.
