### ISSUE TITLE
UNO WiFi with Espressif AT firmware - Blynk

### ISSUE THREAD

**Issue by vsavic** [jandrassy/UnoWiFiDevEdSerial1#4]
I tried to use blynk example with UNO WiFi with Espressif AT firmware, but nothing happens, and nothing is logged in console as well.

Can Blynk be used with this firmware or it works only with `UNO WiFi with WiFi Link firmware`?

**Comment by JAndrassy** [comment]
it should work with AT firmware like it works (or doesn't) for any Atmega328p with esp8266 attached to Serial1. Blynk uses the WiFiEsp library for AT firmware. But common is SoftwareSerial at 9600 baud (set in AT firmware too) and with Uno WiFi you can go at 115200 baud over Serial1.

try the WiFiEspWebClient from Uno WiFi Serial1 examples first with AT firmware.

for Blynk with WiFiLink there is an example in Uno WiFi Serial1 library

**Comment by vsavic** [comment]
WiFiEspWebClient example works fine, I'm able to connect to my wifi network and to get response from server. But when I try UnoWiFiBlynk example, code enter this section:
```
while (WiFi.status() != WL_CONNECTED) {
    delay(10);
  }
```

And it hangs there.

**Comment by JAndrassy** [comment]
UnoWiFiBlynk example is for WiFiLink firmware. 

with AT firmware take [the original Blynk example](https://examples.blynk.cc/?board=Arduino%20Uno&shield=ESP8266%20WiFi%20Shield&example=GettingStarted%2FBlynkBlink) 

It doesn't use WiFiEsp library. my mistake

**Comment by vsavic** [comment]
But, for AT firmware then, should I be using your library then?

```
#include <UnoWiFiDevEdSerial1.h>
#include "WiFiEsp.h"
```
vs
```
#include <ESP8266_Lib.h>
#include <BlynkSimpleShieldEsp8266.h>
```

**UPDATE**
IT WORKS! :)

I had to use this setup:
```
#include <UnoWiFiDevEdSerial1.h>
#include <BlynkSimpleShieldEsp8266.h>
```

And to change this part:
```
Serial.begin(9600);

  // Set ESP8266 baud rate
  Serial1.begin(115200);

  
  ESP8266 wifi(&Serial1);
  delay(10);
```

And now my HW is connected on Blynk!

Thanks for your help!
