### ISSUE TITLE
UnoWiFiDevEdSerial1 ThingSpeak

### ISSUE THREAD

**Issue by russilui** [jandrassy/UnoWiFiDevEdSerial1#5]
Dear jandrassy,

First, thank you for the great job made with this library. I am an engineer and I started working with Arduino a few months ago. 

Merging ThingSpeak example with UNO WiFi Developer Edition Serial1 example I managed to make the Arduino Uno Wifi work with ThingSpeak and I would like to share the result with others which may find it useful. 
Since I am not a coding/GitHub expert, I would like discuss with you the best practice to reach this goal. 

Should I fork/clone this repo, thingspeak repo or both?

Best regards

russilui

**Comment by JAndrassy** [comment]
this library is a gateway between ATmega and esp8266 but doesn't do any networking. is is simply used on Uno WiFi where normal Uno with esp8266 module uses SoftwareSerial.
the documentation and Wiki are broader and describe the Uno WiFi and how to use it with available firmwares.
I am sure your example for ThingsSpeak is not specialized for Uno WiFi and this library. Usually to access ThinkSpeak the code is the same for any of the Arduino  networking libraries
