### ISSUE TITLE
Problem flashing

### ISSUE THREAD

**Issue by jpslootmans** [jandrassy/UnoWiFiDevEdSerial1#6]
Hello Juraj, followed your guide "UNO WiFi (Developer Edition) Serial1" to flash the "ESP8266_NonOS_AT_Bin_V1.7.4" firmware on an Arduino Uno Wifi Rev 3.
All went well until the step "Checking the firmware". After running the tool "EspProxy.ino" with "//#define FLASHING" I get the message you described but then a lot more, which keeps flooding the serial monitor:

2nd boot version : 1.7(5d6f877)
SPI Speed : 80MHz
SPI Mode : QIO
SPI Flash Size & Map: 32Mbit(512KB+512KB)
jump to run user1 @ 1000

correct flash map
mismatch map 2,spi_size_map 4
system param partition error
system_partition_table_regist fail
V2
Mo
rf_cal[0] !=0x05,is 0xFF

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x40100000, len 2592, room 16 
tail 0
chksum 0xf3
load 0x3ffe8000, len 764, room 8 
tail 4
chksum 0x92
load 0x3ffe82fc, len 676, room 4 
tail 0
chksum 0x22
csum 0x22

What can I do to correct this behaviour?
Tried to flash again using the same procedure but then I get the message that esptool cannot connect to the COM Port anymore. Thanks jn advance for your advice
JP Slootmans

**Comment by JAndrassy** [comment]
what is "Arduino Uno Wifi Rev 3."? 
R3 is Uno and Mega pinout revision, 
but Uno WiFi is "Developer Edition" or Rev. 2
this library is only for the retired "Arduino Uno WiFi Developer Edition" made by arduino.org

**Comment by jpslootmans** [comment]
It says: "Board Model UNO WIFI R3" In my mind that meant rev 3. In the right bottom corner there is indeed "Developer edition".
![afbeelding](https://user-images.githubusercontent.com/24653858/99908932-c6d65400-2ce5-11eb-9192-33181b450038.png)

**Comment by JAndrassy** [comment]
ok. it is the "Developer Edition". 

the esptool command for 1.7.4 is here:
https://github.com/jandrassy/WiFiEspAT#at-17-1

only use the  esp_init_data_default.bin for [40 MHz crysta](https://github.com/jandrassy/UnoWiFiDevEdSerial1#prepare)l

**Comment by jpslootmans** [comment]
Hello, tried again with the new 1.7.4 instruction. Now the Serial monitor doesn't go crazy anymore, but I get this:


 ets Jan  8 2Speed : 40MHz
SPI Mode : QIO
SPI Flash Size & Map: 16Mbit(1024KB+1024KB)
jump to run user1 @ 1000


 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x40100000, len 2592, room 16 
tail 0
chksum 0xf3
load 0x3ffe8000, len 764, room 8 
tail 4
chksum 0x92
load 0x3ffe82fc, len 676, room 4 
tail 0
chksum 0x22
csum 0x22

2nd boot version : 1.7(5d6f877)
SPI Speed : 40MHz
SPI Mode : QIO
SPI Flash Size & Map: 16Mbit(1024KB+1024KB)
jump to run user1 @ 1000

correct flash map
V2
Mo
⸮rf cal sector: 507
freq trace enable 0
rf[112] : 00
rf[113] : 00
rf[114] : 01

SDK ver: 3.0.4(9532ceb) compiled @ May 22 2020 16:26:04
phy ver: 1156_0, pp ver: 10.2

`J⸮⸮
The only reaction to the AT commands is some rubbish.
I noticed while flashing this message: WARNING: Detected crystal freq 20.39MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?
Crystal is 26MHz
Which bin should I use?
Kindest regards,
JP

**Comment by JAndrassy** [comment]
the message about crystal is expected.
did you use the  esp_init_data_default.bin for [40 MHz crysta](https://github.com/jandrassy/UnoWiFiDevEdSerial1#prepare)?

what baud rate do you have set in Serial Monitor?

**Comment by jpslootmans** [comment]
Hello Juraj, 

success!
tried with the new 1.7.4 instruction for 1MB and now the response for "AT" = OK. The other instructions all respond as expected.

I guess OTA updating is not possible anymore without giving up the persistent Wifi?
Thanks again for your assitence and patience.
JP

**Comment by JAndrassy** [comment]
the esp8266 on Uno WiFi has a 4 MB flash.
yes, AVR OTA to ATmega328p is not possible with AT firmware
